HotelBooking/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HotelBooking.DataContext;
using HotelBooking.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace HotelBooking.Controllers
{
    [Authorize(Roles ="Admin")]
    public class AdministrationController : Controller
    {

        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ApplicationDbContext context;

        public AdministrationController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager,
            ApplicationDbContext context)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
            this.context = context;
        }


        public IActionResult ListUsers()
        {
            var users = userManager.Users;
            return View(users);
        }

        // Usuwam Usera i przekazuje w metodzie id usera. Używając tego przychodzącego id chce uzyskać określonego usera z bazy danych
        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {
            // znajdź usera po Id
            var user = await userManager.FindByIdAsync(id);

            // jeżeli nie ma usera
            if (user == null)
            {
                ViewBag.Errormessage = $"User z ID = {id} nie został znaleziony.";
                return View("NotFound");
            }

            // w przeciwnym razie korzystam z servicu userManager i wywołuje metodę DeleteAsync w której przekazuje usera do usunięcia.
            else
            {
                var result = await userManager.DeleteAsync(user);

                // jeżeli udało się uzunąć użytkownika
                if (result.Succeeded)
                {
                    //wróc do widoku ListUsers
                    return RedirectToAction("ListUsers");
                }

                // dla każdego errora w result podczas usuwania usera
                foreach (var error in result.Errors)
                {
                    // dodaje errory do ModelState
                    ModelState.AddModelError("", error.Description);
                }
                return View("ListUsers");
            }
        }
    }
}

HotelBooking/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HotelBooking.DataContext;
using HotelBooking.Models;
using HotelBooking.Repositories;
using HotelBooking.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Rotativa.AspNetCore;

namespace HotelBooking.Controllers
{
    
    public class ReservationController : Controller
    {
        //atrybut readonly uniemożliwia przypadkowe nadanie nowej wartości polu _reservationRepository
        private readonly ReservationRepository _reservationRepository;
        private readonly RoomRepository _roomRepository;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly ApplicationDbContext context;
        public ReservationController(ReservationRepository reservationRepository, RoomRepository roomRepository,
            UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, ApplicationDbContext context)
        {
            _reservationRepository = reservationRepository;
            _roomRepository = roomRepository;
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.context = context;
        }

        // Tutaj wyświetlam wszystkie rezerwacje
        [Authorize(Roles = "Admin")]
        public ViewResult GetAllReservations()
        {
            var reservations = _reservationRepository.GetAllReservations()
                .OrderBy(c=>c.CheckInDate);        
            //var model = _reservationRepository.GetAllReservations();
            //model.OrderBy(c => c.TotalPrice);
            ViewBag.TerazJest = DateTime.Now;
            //return View(model);
            return View(reservations);
        }

        // Rezerwuje klient - get
        [HttpGet]
        [Authorize]
        public ViewResult CreateReservation(int id)
        {
            ReservationViewModel reservation = new ReservationViewModel();
            reservation.RoomID = _roomRepository.GetRoom(id).RoomID;
            reservation.UserID = userManager.GetUserId(User);
            return View(reservation);
        }

        // Rezerwuje klient  - post
        [HttpPost]
        [Authorize]
        public RedirectToActionResult CreateReservation(ReservationViewModel reservation)
        {
            if (reservation.CheckInDate < DateTime.Today)
            {
                return RedirectToAction("ReservationLate");
            }

            else if (reservation.CheckInDate == reservation.CheckOutDate)
            {
                return RedirectToAction("ReservationTooShort");
            }

            else if (reservation.CheckInDate > reservation.CheckOutDate)
            {
                return RedirectToAction("ReservationWronglyScheduled");
            }

            else if (context.Reservations.Where(x => x.CheckInDate == reservation.CheckInDate && x.Room.RoomID == reservation.Room.RoomID).Any())
            {
                return RedirectToAction("ReservationExists");
            }

            else
            {
                Models.Reservation reservationModel = new Models.Reservation();

                reservationModel.Room = context.Rooms.FirstOrDefault(x => x.RoomID == reservation.Room.RoomID);
                reservationModel.UserName = userManager.GetUserName(User);
                reservationModel.CheckInDate = reservation.CheckInDate;
                reservationModel.CheckOutDate = reservation.CheckOutDate;
                reservationModel.TotalPrice = reservation.TotalPrice;
                reservationModel.CountDays = reservation.CountDays;

                if (reservationModel.CheckInDate.HasValue && reservationModel.CheckOutDate.HasValue)
                {
                    DateTime dt1 = reservationModel.CheckInDate.Value;
                    DateTime dt2 = reservationModel.CheckOutDate.Value;

                    reservationModel.CountDays = (dt2 - dt1).Days;

                    reservationModel.TotalPrice = reservationModel.CountDays * reservationModel.Room.Price;

                    Reservation newReservation = _reservationRepository.Add(reservationModel);
                    context.SaveChanges();
                }  
            }
            return RedirectToAction("MyReservation");
        }

        public IActionResult ReservationExists()
        {
            return View();
        }

        public IActionResult ReservationLate()
        {
            return View();
        }

        public IActionResult ReservationTooShort()
        {
            return View();
        }

        public IActionResult ReservationWronglyScheduled()
        {
            return View();
        }


        // Tutaj Klient dokonuje rezerwacji
        [Authorize]
        public IActionResult Reservation(int id)
        {
            ReservationViewModel reservationViewModel = new ReservationViewModel()
            {
                UserID = userManager.GetUserId(User),
                Room = _roomRepository.GetRoom(id),
                RoomID = _roomRepository.GetRoom(id).RoomID,
            };

            return View(reservationViewModel);
        }


        // Po dokonaniu rezerwacji, klient przechodzi do Podsumowania  - ReservationDetails
        [Authorize]
        public ViewResult ReservationDetails(int id)
        {
            ReservationDetailsViewModel reservationDetailsViewModel = new ReservationDetailsViewModel()
            {

                UserID = userManager.GetUserId(User),
                Reservation = _reservationRepository.GetReservation(id),
                Room = _roomRepository.GetRoom(id),
            };

            return View(reservationDetailsViewModel);
        }

        // Po rezerwacji pokoju, podsumowanie można zapisać do PDF
        [Authorize]
        public async Task<IActionResult> ReservationPDF(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await context.Reservations
                .FirstOrDefaultAsync(m => m.ReservationID == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return new ViewAsPdf(reservation);
        }

        // Tutaj wyświetlają się rezerwacje zalogowanego klienta
        [Authorize]
        public async Task<IActionResult> MyReservation(int id)
        {  
            
            ApplicationUser user = await GetCurrentUserAsync();
            var reservation = _reservationRepository.GetAllReservations();
            //.Where(p => p.UserName == user.UserName)
            //.OrderBy(c => c.CheckInDate);
            reservation = reservation.Where(p => p.UserName == user.UserName);
            reservation = reservation.OrderBy(c => c.CheckInDate);

            if (reservation.Any())
            {
                ViewBag.TerazJest = DateTime.Now;
                return View(reservation);
            }

            else
            {
                return View ("NoReservation");
            }
        }

        //public IActionResult NoReservation()
        //{
        //    return View();
        //}

        private Task<ApplicationUser> GetCurrentUserAsync() => userManager.GetUserAsync(HttpContext.User);

        // Edytuję rezerwację
        [HttpGet]
        [Authorize]
        public ViewResult EditReservation(int id)
        {
            Reservation reservation = _reservationRepository.GetReservation(id);
            ReservationEditViewModel reservationEditViewModel = new ReservationEditViewModel
            {
                ReservationID = reservation.ReservationID,
                RoomID = reservation.RoomID,
                TotalPrice = reservation.TotalPrice,
                UserName = reservation.UserName,
                CheckInDate = reservation.CheckInDate,
                CheckOutDate = reservation.CheckOutDate,
                CountDays = reservation.CountDays,
            };
            return View(reservationEditViewModel);
        }

        // Dokonuję zmian w edytowanej rezerwacji
        [HttpPost]
        [Authorize]
        public IActionResult EditReservation(ReservationEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                Reservation reservation = _reservationRepository.GetReservation(model.ReservationID);
                reservation.RoomID = model.RoomID;
                reservation.UserName = model.UserName;
                reservation.CheckInDate = model.CheckInDate;
                reservation.CheckOutDate = model.CheckOutDate;
                reservation.TotalPrice = model.TotalPrice;
                reservation.CountDays = model.CountDays;
                

                if (reservation.CheckInDate < DateTime.Today)
                {
                    return RedirectToAction("ReservationLateEdit");
                }

                if (reservation.CheckInDate == reservation.CheckOutDate)
                {
                    return RedirectToAction("ReservationTooShortEdit");
                }

                if (reservation.CheckInDate > reservation.CheckOutDate)
                {
                    return RedirectToAction("ReservationWronglyScheduledEdit");
                }

                _reservationRepository.Update(reservation);

                //Aktualizacja ilości dni i nowej ceny cłkowitej
                if (reservation.CheckInDate.HasValue && reservation.CheckOutDate.HasValue)
                {
                    DateTime dt1 = reservation.CheckInDate.Value;
                    DateTime dt2 = reservation.CheckOutDate.Value;

                    reservation.CountDays = (dt2 - dt1).Days;

                    var roomId = reservation.RoomID;

HotelBooking/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using HotelBooking.DataContext;
using HotelBooking.Models;
using HotelBooking.Repositories;
using HotelBooking.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace HotelBooking.Controllers
{
    public class RoomController : Controller
    { // dependency injection przez konstruktor
        private readonly RoomRepository _roomRepository;
        private readonly IHostingEnvironment hostingEnvironment;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ApplicationDbContext _context;

        public RoomController(RoomRepository roomRepository, IHostingEnvironment hostingEnvironment,
            UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _roomRepository = roomRepository;
            this.hostingEnvironment = hostingEnvironment;
            this.userManager = userManager;
            _context = context;
        }

        // List of rooms for a customer
        public ViewResult NewRooms()
        {
            var model = _roomRepository.GetAllRooms();
            return View(model);
        }

        // List of rooms for an administrator
        [Authorize(Roles = "Admin")]
        public ViewResult Index()
        {
            var model = _roomRepository.GetAllRooms();
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public ViewResult Details(int id)
        {
            HomeDetailsViewModel homeDetailsViewModel = new HomeDetailsViewModel()
            {
                Room = _roomRepository.GetRoom(id),
                PageTitle = "Room Details"
            };

            return View(homeDetailsViewModel);
        }


        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ViewResult Edit(int id)
        {
            Room room = _roomRepository.GetRoom(id);
            RoomEditViewModel roomEditViewModel = new RoomEditViewModel
            {
                RoomID = room.RoomID,
                RoomNumber = room.RoomNumber,
                Type = room.Type,
                Price = room.Price,
                Description = room.Description,
                ExistingPhotoPath = room.PhotoPath
            };
            return View(roomEditViewModel);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Edit(RoomEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                Room room = _roomRepository.GetRoom(model.RoomID);
                room.RoomNumber = model.RoomNumber;
                room.Type = model.Type;
                room.Price = model.Price;
                room.Description = model.Description;


                if (model.Photo != null)
                {
                    if (model.ExistingPhotoPath != null)
                    {
                        string filePath = Path.Combine(hostingEnvironment.WebRootPath, "Images", model.ExistingPhotoPath);
                        System.IO.File.Delete(filePath);
                    }
                    room.PhotoPath = ProcessUploadedFile(model);
                }

                _roomRepository.Update(room);

                return RedirectToAction("NewRooms");
            }
            return View();
        }

        [Authorize(Roles = "Admin")]
        private string ProcessUploadedFile(RoomCreateViewModel model)
        {
            string uniqueFileName = null;

            if (model.Photo != null)
            {
                string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "Images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Photo.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Create(RoomCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = ProcessUploadedFile(model);
                Room newRoom = new Room
                {
                    Type = model.Type,
                    RoomNumber = model.RoomNumber,
                    Price = model.Price,
                    Description = model.Description,
                    PhotoPath = uniqueFileName
                };

                _roomRepository.Add(newRoom);

                return RedirectToAction("details", new { id = newRoom.RoomID });
            }
            return View();
        }

        [Authorize(Roles = "Admin")]
        public Room Delete(int id)
        {
            // before deleting a Pacjent, we need to find them first
            Room room = _context.Rooms.Find(id);
            if (room != null)
            {
                _context.Rooms.Remove(room);
                _context.SaveChanges();
            }
            return room;
        }

    }
}

HotelBooking/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager



<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Grand Royale</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy;@DateTime.Today.ToShortDateString() | Grand Royale Bydgoszcz | ul. Gdańska 21 | telefon: 347-764-238 | grandroyale@kontakt.pl | NIP: 977 4246 76
    </div>

</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@RenderSection("Scripts", required: false)


@if (!SignInManager.IsSignedIn(User))
{

    <!DOCTYPE html>
    <html lang="en">

    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Grand Royale</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">

                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Home" asp-action="About">O nas</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Home" asp-action="Contact">Kontakt</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Home" asp-action="Rooms">Galeria</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Room" asp-action="NewRooms">Pokoje i Apartamenty</a>
                            </li>

                        </ul>
                    </div>

                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">

                @RenderBody()

            </main>
        </div>
    </body>
</html>

}

@*Zalogowany użytkownik, który jest Adminem*@
@if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))

{

    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Grand Royale</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">

                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Home" asp-action="About">O nas</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Home" asp-action="Contact">Kontakt</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Home" asp-action="Rooms">Galeria</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Room" asp-action="NewRooms">Pokoje i Apartamenty</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-outline-warning" asp-controller="Reservation" asp-action="GetAllReservations">Wszystkie rezerwacje</a>|      |
                            </li>
                            <div class="btn-group">
                                <button class="btn btn-outline-warning btn-group-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Panel administratora
                                </button>
                                <div class="dropdown-menu">
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-controller="Room" asp-action="Create">Dodaj pokój</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-controller="Room" asp-action="Index">Zarządzaj pokojami</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-controller="Account" asp-action="Register">Dodaj klienta</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-controller="Administration" asp-action="ListUsers">Zarządzaj klientami</a>
                                </div>
                            </div>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">

                @RenderBody()

            </main>
        </div>
    </body>

}

@if (SignInManager.IsSignedIn(User) && !(@UserManager.GetUserAsync(User).Result.UserName == "lfarulewski@yahoo.com"))

{

    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Grand Royale</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">

                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            @*<li class="nav-item">
            <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Home</a>
        </li>*@

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Home" asp-action="About">O nas</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Home" asp-action="Contact">Kontakt</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Home" asp-action="Rooms">Galeria</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Room" asp-action="NewRooms">Pokoje i Apartamenty</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-outline-info" asp-controller="Room" asp-action="NewRooms">Idź do rezerwacji</a>|            |
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-outline-info" asp-controller="Reservation" asp-action="MyReservation">Moje rezerwacje</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">

                @RenderBody()

            </main>
        </div>
    </body>

}



@if (IsSectionDefined("site"))

{

    @RenderSection("site", required: true);

}